export enum ApiErrorCode {
  // 400
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_LOCALE = 'INVALID_LOCALE',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  UPLOAD_NOT_ALLOWED = 'UPLOAD_NOT_ALLOWED',

  // 401
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  CANDIDATE_SESSION_REQUIRED = 'CANDIDATE_SESSION_REQUIRED',
  INVALID_CANDIDATE_SESSION = 'INVALID_CANDIDATE_SESSION',
  INTERVIEW_TOKEN_REQUIRED = 'INTERVIEW_TOKEN_REQUIRED',
  INVALID_INTERVIEW_TOKEN = 'INVALID_INTERVIEW_TOKEN',

  // 403
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // 404
  NOT_FOUND = 'NOT_FOUND',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  INTERVIEW_NOT_FOUND = 'INTERVIEW_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FEEDBACK_NOT_FOUND = 'FEEDBACK_NOT_FOUND',

  // 409
  CONFLICT = 'CONFLICT',
  QUESTION_IN_USE = 'QUESTION_IN_USE',
  VALIDATION_RUNNING = 'VALIDATION_RUNNING',
  QUESTION_DUPLICATE = 'QUESTION_DUPLICATE',

  // 503
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  AI_PROVIDER_NOT_CONFIGURED = 'AI_PROVIDER_NOT_CONFIGURED',
  EMBEDDING_PROVIDER_NOT_CONFIGURED = 'EMBEDDING_PROVIDER_NOT_CONFIGURED',

  // 500
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

const API_ERROR_CODE_SET = new Set<string>(Object.values(ApiErrorCode));

export function isApiErrorCode(value: string): value is ApiErrorCode {
  return API_ERROR_CODE_SET.has(value);
}
